/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcul.h"


void
cal_bin_prog_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *calnull_1_arg;
	long  *result_2;
	p  puiss_1_arg;
	long  *result_3;
	int  dec2bin_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CAL_BIN_PROG, CAL_VERS_ONE, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = calnull_1((void*)&calnull_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = puiss_1(&puiss_1_arg, clnt);
	if (result_2 == (long *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = dec2bin_1(&dec2bin_1_arg, clnt);
	if (result_3 == (long *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
cal_bin_prog_2(char *host)
{
	CLIENT *clnt;
	chaine  *result_1;
	int  dec2hex_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CAL_BIN_PROG, CAL_VERS_TWO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = dec2hex_2(&dec2hex_2_arg, clnt);
	if (result_1 == (chaine *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	cal_bin_prog_1 (host);
	cal_bin_prog_2 (host);
exit (0);
}
